/* Consulta núemro 2: Listar os 5 maiores fornecedores de alimento, que são pessoas juridicas, que foram cadastrados no ano de 2017 */

SELECT TOP 5 MAX(COUNT(P.ID_PESSOA)) FROM FORNECEDOR F

INNER JOIN ALIMENTO A ON F.ID_FORNECEDOR = A.ID_FORNECEDOR
INNER JOIN PESSOA P ON P.ID_PESSOA = F.ID_PESSOA
INNER JOIN PESSOA_JURIDICA PJ ON PJ.ID_PESSOA = P.ID_PESSOA

WHERE

YEAR(P.DATA_HORA_CAD) = 2017