/* Consulta número 3: Listar os 10 produtos mais vendidos. */

SELECT TOP 10 P.ID_PRODUTO, P.NOME, P.TIPO, 
SUM(P.QUANTIDADE) as QUANTIDADE FROM PRODUTO P  
GROUP BY P.ID_PRODUTO, P.NOME, P.TIPO
ORDER BY QUANTIDADE DESC, P.NOME, P.TIPO